name: Static Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - release
  push:
    branches:
      - develop
      - release

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Build and test static base
        run: |
          docker build -f docker/Dockerfile.static-base -t ns1labs/static-base .

      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Debug branch name
        run: echo ${{ env.BRANCH_NAME }}

      - name: Get VERSION
        run: |
          echo "VERSION=`docker run --rm -a stdout --entrypoint cat ns1labs/static-base VERSION`" >> $GITHUB_ENV

      - name: Debug version
        run: echo ${{ env.VERSION }}

      - name: Generate ref tag (master)
        if: ${{ env.BRANCH_NAME == 'master' }}
        run: |
          echo "REF_TAG=latest" >> $GITHUB_ENV
          echo "PRERELEASE=false" >> $GITHUB_ENV
          echo "DRAFT=true" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        if: ${{ env.BRANCH_NAME == 'develop' }}
        run: |
          echo "REF_TAG=latest-develop" >> $GITHUB_ENV
          echo "PRERELEASE=true" >> $GITHUB_ENV
          echo "DRAFT=false" >> $GITHUB_ENV

      - name: Generate ref tag (release candidate)
        if: ${{ env.BRANCH_NAME == 'release' }}
        run: |
          echo "REF_TAG=latest-rc" >> $GITHUB_ENV
          echo "PRERELEASE=true" >> $GITHUB_ENV
          echo "DRAFT=false" >> $GITHUB_ENV

      - name: Debug ref tag
        run: echo ${{ env.REF_TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and package static pktvisord
#        if: github.event_name != 'pull_request'
        env:
          BASE_BINARY: pktvisord
          IMAGE_NAME: ns1labs/pktvisord-slim
        run: |
          docker build -f docker/Dockerfile.${{ env.BASE_BINARY }}-static -t ${{ env.IMAGE_NAME }} .
          docker push -a ${{ env.IMAGE_NAME }}
          echo "CONT_ID=$(docker create --name ${{ env.BASE_BINARY }}-slim-tmp ${{ env.IMAGE_NAME }})" >> $GITHUB_ENV
          docker cp ${{ env.CONT_ID }}:/${{ env.BASE_BINARY }} ${{github.workspace}}/pktvisord-linux-x86_64-${{ env.VERSION }}

      - name: Upload pktvisord artifact
#        if: github.event_name != 'pull_request'
        env:
          BINARY_NAME: pktvisord-linux-x86_64-${{ env.VERSION }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{github.workspace}}/${{ env.BINARY_NAME }}

      - name: Build static pktvisor-pcap-slim
        if: github.event_name != 'pull_request'
        env:
          IMAGE_NAME: ns1labs/pktvisor-pcap
        run: |
          docker build -f docker/Dockerfile.pktvisor-pcap-static -t ${{ env.IMAGE_NAME }} .
          docker push -a ${{ env.IMAGE_NAME }}

      - name: Build static pktvisord-dnstap
        if: github.event_name != 'pull_request'
        env:
          IMAGE_NAME: ns1labs/pktvisor-pcap-slim
        run: |
          docker build -f docker/Dockerfile.pktvisor-dnstap-static -t ${{ env.IMAGE_NAME }} .
          docker push -a ${{ env.IMAGE_NAME }}

